config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'posts#index'

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: '/letter_opener'
    require 'sidekiq/web'
    mount Sidekiq::Web, at: '/sidekiq'
  end

  resources :likes, only: [:create, :destroy]

  # shallowを使う事でurlの親のidを省略
  resources :posts, shallow: true do
    collection do
      get :search
    end
    resources :comments, only: [:create, :edit, :update, :destroy]
  end

  get 'search', to: 'posts#search'

  resources :users do
    member do
      get :follow, :followed
    end
  end

  resources :relationships, only: [:create, :destroy]

  namespace :mypage do
    # 今回はurlにidが不要なためresourcesではなく、resourceを使う
    resource :account, only: [:edit, :update]
    # プロフィールの通知一覧
    resources :notifications, only: :index
    # notificationの通知設定
    resource :notification_setting, only: [:edit, :update]
  end

  # ヘッダーの通知一覧
  scope module: :mypage do
    resources :notifications, only: [] do
      patch :read, on: :member
    end
  end

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                      :bigint           not null, primary key
#  avatar                  :string(255)
#  crypted_password        :string(255)
#  email                   :string(255)      not null
#  name                    :string(255)      not null
#  notification_on_comment :boolean          default(TRUE)
#  notification_on_follow  :boolean          default(TRUE)
#  notification_on_like    :boolean          default(TRUE)
#  salt                    :string(255)
#  created_at              :datetime         not null
#  updated_at              :datetime         not null
#
# Indexes
#
#  index_users_on_email  (email) UNIQUE
#
class User < ApplicationRecord
  authenticates_with_sorcery!

  validates :password, length: { minimum: 3 }, if: -> { new_record? || changes[:crypted_password] }
  validates :password, confirmation: true, if: -> { new_record? || changes[:crypted_password] }
  validates :password_confirmation, presence: true, if: -> { new_record? || changes[:crypted_password] }
  validates :name, presence: true, uniqueness: true
  validates :email, presence: true, uniqueness: true

  mount_uploader :avatar, ImageUploader

  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy

  has_many :likes, dependent: :destroy
  # likesのデータが入ったpostを直接取得する事ができる
  has_many :like_posts, through: :likes, source: :post

  # notificationのアソシエーション
  has_many :notifications, dependent: :destroy

  has_many :follow_relationships, foreign_key: 'follow_id', class_name: 'Relationship', dependent: :destroy
  has_many :follows, through: :follow_relationships, source: :followed
  has_many :followed_relationships, foreign_key: 'followed_id', class_name: 'Relationship', dependent: :destroy
  has_many :followed, through: :followed_relationships, source: :follow

  # defで関数を定義するかscopeを使うかは好みの問題

  def follow(other_user)
    follow_relationships.create(followed_id: other_user.id)
  end

  def unfollow(other_user)
    follow_relationships.find_by(followed_id: other_user.id).destroy
  end

  def follow?(other_user)
    follows.include?(other_user)
  end

  def own?(object)
    id == object.user_id
  end

  # ポストをいいねする
  def like(post)
    # Like.newせずとも新しいレコードがインサートする。とても便利なメソッド。
    like_posts << post
  end

  # ポストのいいねを解除する
  def unlike(post)
    like_posts.destroy(post)
  end

  # その投稿にいいねがあるかどうか
  def like?(post)
    like_posts.include?(post)
  end

  def feed
    # Postsテーブルのuser_idカラムからuserがフォローしているidの配列を取得しているかつその配列にcurrent_userのidも配列に加えてSQL内を検索している。
    Post.where(user_id: follow_ids << id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :require_login, only: [:index, :new, :create, :show]

  def index
    @users = User.order(id: :desc).page(params[:page]).per(10)
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      # postsへリダイレクト
      auto_login(@user)
      redirect_to root_url, success: 'ユーザーの作成に成功しました'
    else
      flash[:danger] = 'ユーザーの作成に失敗しました'
      render :new
    end
  end

  def show
    @user = User.find(params[:id])
    @posts = @user.posts
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_follow.html.slim
//modelオプションを調べる！挙動がよくわかっていないので
= form_with(model: current_user.follow_relationships.build) do |f|
  = f.hidden_field :followed_id, value: user.id
  = f.submit "フォロー", class: "btn btn-raised btn-outline-warning", id: "follow"

app/views/users/_follow_area.html.slim
- if logged_in? && user != current_user
  div id = "follow-area-#{user.id}"
    - if current_user.follow?(user)
      = render "users/unfollow", user: user
    - else
      = render "users/follow", user: user

app/views/users/_unfollow.html.slim
= form_with(model: current_user.follow_relationships.find_by(followed_id: user.id), method: :delete) do |f|
  = f.hidden_field :followed_id, value: user.id
  = f.submit "アンフォロー", class: "btn btn-warning btn-raised", id: "unfollow"

app/views/users/_user.html.slim
.user.mb-3.d-flex.justify-content-between
  = link_to user_path(user) do
    = image_tag  user.avatar.url, class: "rounded-circle mr-1", width: "40", height: "40"
    = user.name
  = render 'users/follow_area', user: user
hr

app/views/users/index.html.slim
- set_meta_tags title: "ユーザー一覧ページ"
.container
  .row
    .col-md-6.col-12.offset-md-3.mb-3
      .card
        .card-body
          = render @users
    .col-md-6.col-12.offset-md-3
      = paginate @users

app/views/users/new.html.slim
.login-register-form
  .login-register-form-inner
    .card.mb-3
      = form_with model: @user, class: 'card-body', local: true do |f|
        = render 'shared/error_messages', object: @user
        .form-group
          = f.label :name, class: 'bmd-label-floating'
          = f.text_field :name, class: 'form-control'
        .form-group
          = f.label :email, class: 'bmd-label-floating'
          = f.text_field :email, class: 'form-control'
        .form-group
          = f.label :password, class: 'bmd-label-floating'
          = f.password_field :password, class: 'form-control'
        .form-group
          = f.label :password_confirmation, class: 'bmd-label-floating'
          = f.password_field :password_confirmation, class: 'form-control'
        = f.submit '登録', class: 'btn btn-raised btn-primary'
    .card
      .card-body
        | アカウントをお持ちですか
        = link_to  "ログインする", login_path

app/views/users/show.html.slim
- set_meta_tags title: 'ユーザー詳細ページ'
.container
  .row
    .col-md-10.offset-md-1
      .card
        .card-body
          - if current_user&.id == @user.id
            .text-center.mb-3
              = link_to 'プロフィール編集', edit_mypage_account_path, class: 'btn btn-raised btn-warning'
          .text-center.mb-3
            = image_tag @user.avatar.url, size: '100x100', class: 'rounded-circle mr-1'
          .profile.text-center.mb-3
            = @user.name
          .text-center
            = render 'follow_area', user: @user
          hr
          .row
            = render partial: 'posts/thumbnail_post', collection: @user.posts