config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'posts#index'

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: '/letter_opener'
    require 'sidekiq/web'
    mount Sidekiq::Web, at: '/sidekiq'
  end

  resources :likes, only: [:create, :destroy]

  # shallowを使う事でurlの親のidを省略
  resources :posts, shallow: true do
    collection do
      get :search
    end
    resources :comments, only: [:create, :edit, :update, :destroy]
  end

  get 'search', to: 'posts#search'

  resources :users do
    member do
      get :follow, :followed
    end
  end

  resources :relationships, only: [:create, :destroy]

  namespace :mypage do
    # 今回はurlにidが不要なためresourcesではなく、resourceを使う
    resource :account, only: [:edit, :update]
    # プロフィールの通知一覧
    resources :notifications, only: :index
    # notificationの通知設定
    resource :notification_setting, only: [:edit, :update]
  end

  # ヘッダーの通知一覧
  scope module: :mypage do
    resources :notifications, only: [] do
      patch :read, on: :member
    end
  end

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
end

app/views/shared/_before_login_header.html.slim
.navbar.navbar-expand-lg.navbar-light.bg-white
  = link_to  "InstaClone", root_path , class: 'navbar-brand'
  .collapse.navbar-collapse#navbarTogglerDemo02
    ul.navbar-nav.mt-2.mt-lg-0
        li.nav-item
          = link_to "ポスト一覧", root_path, class: 'nav-link'
        li.nav-item
          = link_to "ログイン", login_path, class: 'nav-link'

app/views/shared/_commented_to_own_post.html.slim
= link_to read_notification_path(notification), class: "dropdown-item border-bottom #{'read' if notification.read?}", method: :patch do
  = image_tag "default.png", class: "rounded-circle mr-1", size: '30x30'
  object
    = link_to notification.subject.user.name, user_path(notification.subject.user)
  | があなたの
  object
    = link_to '投稿', post_path(notification.subject.post)
  | に
  object
    = link_to 'コメント', post_path(notification.subject.post, anchor: "comment-#{notification.subject.id}")
  | しました
  .text-right
    = l notification.created_at, format: :short

app/views/shared/_error_messages.html.slim
- if object.errors.any?
  .alert.alert-danger#error_messsages
    -object.errors.full_messages.each do |message|
      li = message

app/views/shared/_flash.html.slim
- flash.each do |key, value|
  div class = "alert alert-#{key}"
    = value

app/views/shared/_header_notifications.html.slim
- if current_user.notifications.present?
  - current_user.notifications.recent(10).each do |notification|
    = render "mypage/notifications/#{notification.action_type}", notification: notification
  - if current_user.notifications.count > 10
    = link_to 'すべてみる', mypage_notifications_path, class: 'dropdown-item justify-content-center'
- else
  .dropdown-item
    | お知らせはありません

app/views/shared/_liked_to_own_post.html.slim
= link_to read_notification_path(notification), class: "dropdown-item border-bottom #{'read' if notification.read?}", method: :patch do
  = image_tag notification.subject.user.avatar.url, class: 'rounded-circle mr-1', size: '30x30'
  object
    = link_to notification.subject.user.username, user_path(notification.subject.user)
  | があなたの
  object
    = link_to '投稿', post_path(notification.subject.post)
  | にいいねしました
  .text-right
    = l notification.created_at, format: :short

app/views/shared/_modal.html.slim
#modal-container

app/views/shared/_swiper.html.slim
javascript:
  var swiper = new Swiper(".swiper-container", {
    pagination: {
      el: ".swiper-pagination",
      dynamicBullets: true,
    },
  });

app/views/shared/_unread_badge.html.slim
- if current_user.notifications.unread.count > 0
  .badge.badge-warning.navbar-badge.position-absolute
    = current_user.notifications.unread.count

app/views/shared/followed_me.html.slim
= link_to read_notification_path(notification), class: "dropdown-item border-bottom #{'read' if notification.read?}", method: :patch do
  = image_tag notification.subject.follow.avatar.url, class: 'rounded-circle mr-1', size: '30x30'
  object
    = link_to notification.subject.follow.name, user_path(notification.subject.follow)
  | があなたをフォローしました
  .text-right
    = l notification.created_at, format: :short