config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'posts#index'

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: '/letter_opener'
    require 'sidekiq/web'
    mount Sidekiq::Web, at: '/sidekiq'
  end

  resources :likes, only: [:create, :destroy]

  # shallowを使う事でurlの親のidを省略
  resources :posts, shallow: true do
    collection do
      get :search
    end
    resources :comments, only: [:create, :edit, :update, :destroy]
  end

  get 'search', to: 'posts#search'

  resources :users do
    member do
      get :follow, :followed
    end
  end

  resources :relationships, only: [:create, :destroy]

  namespace :mypage do
    # 今回はurlにidが不要なためresourcesではなく、resourceを使う
    resource :account, only: [:edit, :update]
    # プロフィールの通知一覧
    resources :notifications, only: :index
    # notificationの通知設定
    resource :notification_setting, only: [:edit, :update]
  end

  # ヘッダーの通知一覧
  scope module: :mypage do
    resources :notifications, only: [] do
      patch :read, on: :member
    end
  end

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
end

app/models/post.rb
# == Schema Information
#
# Table name: posts
#
#  id         :bigint           not null, primary key
#  content    :text(65535)      not null
#  images     :string(255)      not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  user_id    :bigint
#
# Indexes
#
#  index_posts_on_user_id  (user_id)
#
# Foreign Keys
#
#  fk_rails_...  (user_id => users.id)
#
class Post < ApplicationRecord
  mount_uploaders :images, ImageUploader
  serialize :images, JSON

  validates :images, presence: true
  validates :content, presence: true, length: { maximum: 1000 }

  has_many :likes, dependent: :destroy
  has_many :like_users, through: :likes, source: :user
  has_many :comments, dependent: :destroy
  has_one :notification, as: :subject, dependent: :destroy

  belongs_to :user

  # nameが存在する場合、nameをlike検索する
  scope :post_like, ->(post_content) { where('content LIKE ?', "%#{post_content}%") }
  scope :user_like, ->(name) { joins(:user).where('name LIKE ?', "%#{name}%") }
  scope :comment_like, ->(comment_content) { joins(:comments).where('comments.content LIKE ?', "%#{comment_content}%") }
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  skip_before_action :require_login, only: [:index, :show]
  before_action :set_post, only: [:edit, :update, :destroy]

  def index
    @posts = if current_user
               current_user.feed.includes(:user).page(params[:page]).order(created_at: :desc)
             else
               Post.includes(:user).page(params[:page]).order(created_at: :desc)
             end
    @users = User.recent(5)
  end

  def new
    @post = Post.new
  end

  def create
    @post = current_user.posts.new(post_params)
    if @post.save
      redirect_to posts_path, success: '投稿しました'
    else
      flash[:danger] = '投稿に失敗しました'
      render :new
    end
  end

  def edit; end

  def update
    if @post.update(post_params)
      redirect_to root_path, success: '投稿を更新しました'
    else
      flash[:danger] = '投稿の更新に失敗しました'
      render :edit
    end
  end

  def destroy
    @post.destroy
    redirect_to root_path, success: '投稿を削除しました'
  end

  def show
    @post = Post.find(params[:id])
    @comment = Comment.new
    # 新着順で表示、N+1問題に対応するためincludesを用いている
    @comments = @post.comments.includes(:user).order(created_at: :desc)
  end

  def search
    @posts = @search_form.search.includes(:user).page(params[:page])
  end

  private

  def post_params
    params.require(:post).permit(:content, images: [])
  end

  def set_post
    @post = current_user.posts.find(params[:id])
  end
end

app/views/posts/_form.html.slim
= form_with model: post, class: 'form', id: 'posts_form', local: true do |f|
  = render 'shared/error_messages', object: post
  .form-group
    = f.label :images
    = f.file_field :images, multiple: true, class: 'form-control'
      - post.images.each do |image|
        = image_tag image.url, size: '100x100', class: 'image-thumbnail'
  .form-group
    = f.label :content
    = f.text_area :content, class: 'form-control'
  = f.submit '登録する', class: 'btn btn-raised btn-primary'

app/views/posts/_like.html.slim
- if current_user.like?(post)
  = link_to like_path(current_user.likes.find_by(post_id: post.id)), remote: true, method: :delete, class: "unlike-button" do
    .fa.fa-heart.fa-lg
- else
  = link_to likes_path(post_id: post.id), remote: true, method: :post, class: "like-button" do
    .far.fa-heart.fa-lg

app/views/posts/_like_area.html.slim
div id = "like_area-#{post.id}"
  = render "like", post: post

app/views/posts/_post.html.slim
.card.mb-5.post
  div id = "post-#{post.id}"
    .card-header
      .d-flex.align-items-center
        = image_tag  post.user.avatar.url, class: "rounded-circle mr-1", width: "40", height: "40"
        = link_to user_path(post.user) do
          = post.user.name
          /ぼっち演算子を用いてnilを返すようにする/
        - if current_user&.own?(post)
            .ml-auto
              = link_to post_path(post), method: :delete, data: {confirm: "本当に削除しますか？"}, class: "mr-3 delete-button" do
                i class = "far fa-trash-alt fa-lg"
              = link_to edit_post_path(post), class: 'edit-button' do
                i class = "far fa-edit fa-lg"
        - if current_user && !current_user&.own?(post)
            .ml-auto
              div id = "like_area-#{post.id}"
                = render "like", post: post
  = link_to post_path(post) do
    .swiper-container.top-carousel
      .swiper-wrapper
        - post.images.each do |img|
          .swiper-slide
            = image_tag img.url, class: "card-img-top"
      .swiper-pagination
  .card-body
    .card-text = post.content

app/views/posts/_search.html.slim
//application_controller.rbで設定したsearch_formという空のインスタンスに、このフォームで入力されたものがパラメーターに入る。//
//そして、post_controller.rbのsearchアクション内にとびsearch.html.slimが出力される//
= form_with(model: search_form, scope: :search, url: search_posts_path, method: :get, class: "form-inline my-2 my-lg-0 mr-auto", local: true) do |f|
      = f.text_field :post_content, class: "form-control mr-sm-2", placeholder: "本文"
      = f.text_field :comment_content, class: "form-control mr-sm-2", placeholder: "コメント"
      = f.text_field :name, class: "form-control mr-sm-2", placeholder: "ユーザー名"
      = f.submit 'SEARCH', class: "btn btn-outline-success my-2 my-sm-0"

app/views/posts/_thumbnail_post.html.slim
.col-md-4.mb-3
  = link_to post_path(thumbnail_post), class: 'thumbs' do
    = image_tag thumbnail_post.images.first.url

app/views/posts/edit.html.slim
main
  .container
    .row
      .col-md-6.col-12.offset-md-3
        .card
          .card-body
            = render 'form', post: @post

app/views/posts/index.html.slim
.container
    .row
      .col-md-8.col-12
        - if @posts.present?
          = render @posts
        - else
          .text-center.font-weight-bold
            | 投稿がありません
        = paginate @posts
        - if logged_in? && !current_user.posts.present? && !current_user.follows.all.map{ |f| f.posts}.present?
          .text-center.font-weight-bold
            | 誰かをフォローしたらフィードが表示されるよ！！！
      .col-md-4.col-12
        - if logged_in?
          .profile-box.mb-3
              = link_to user_path(current_user) do
                = image_tag  current_user.avatar.url, class: "rounded-circle", id: "avatar_prv", width: "50", height: "50"
                = current_user.name
          .users-box
            .card
              .card-header
                | ユーザー
              .card-body
                = render @users
              .card-footer
                = link_to "すべて見る", users_path

app/views/posts/new.html.slim
main
  .container
    .row
      .col-md-6.col-12.offset-md-3
        .card
          .card-body
            = render "form", post: @post
#modal-container

app/views/posts/search.html.slim
.container
  .row
    .col-md-8.col-12.offset-md-2
      h2.text-center
        | 検索結果: #{@posts.total_count}件
      = render @posts
      = paginate @posts

app/views/posts/show.html.slim
- set_meta_tags title: '投稿詳細ページ', description: @post.content,
        og: { image: "#{@post.images.first.url}"}
.post-detail.card
    .image-box
      .swiper-container
        .swiper-wrapper(style="transform: translate3d(0px, 0px, 0px)")
          - @post.images.each do |img|
            .swiper-slide(style="width: 400px;")
              = image_tag img.swiper.url, class: "card-img-top"
        .swiper-pagination
    .image-info-box
      .profile-box.p-3
        .d-flex.align-items-center
          = image_tag  @post.user.avatar.url, class: "rounded-circle mr-1", width: "40", height: "40"
          = @post.user.name
          - if current_user&.own?(@post)
            .ml-auto
              = link_to post_path(@post), method: :delete, data: {confirm: "本当に削除しますか？"}, class: "mr-3 delete-button" do
                .far.fa-trash-alt.fa-lg
              = link_to edit_post_path(@post), class: "edit-button" do
                .far.fa-edit.fa-lg
          - if current_user && !current_user.own?(@post)
            .ml-auto
              = render 'like_area', post: @post
      hr.m-0
      .post-body.p-3
        .row.no-gutters
          .col-2
            = image_tag  @post.user.avatar.url , class: "rounded-circle mr-1", width: "40", height: "40"
          .col-10
            = simple_format(@post.content)
        hr
        = render "comments/comments", comments: @comments
      hr class = "m-0"
      .post-comment.p-3
        = render 'comments/form', comment: @comment, post: @post