config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'posts#index'

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: '/letter_opener'
    require 'sidekiq/web'
    mount Sidekiq::Web, at: '/sidekiq'
  end

  resources :likes, only: [:create, :destroy]

  # shallowを使う事でurlの親のidを省略
  resources :posts, shallow: true do
    collection do
      get :search
    end
    resources :comments, only: [:create, :edit, :update, :destroy]
  end

  get 'search', to: 'posts#search'

  resources :users do
    member do
      get :follow, :followed
    end
  end

  resources :relationships, only: [:create, :destroy]

  namespace :mypage do
    # 今回はurlにidが不要なためresourcesではなく、resourceを使う
    resource :account, only: [:edit, :update]
    # プロフィールの通知一覧
    resources :notifications, only: :index
    # notificationの通知設定
    resource :notification_setting, only: [:edit, :update]
  end

  # ヘッダーの通知一覧
  scope module: :mypage do
    resources :notifications, only: [] do
      patch :read, on: :member
    end
  end

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
end

app/views/layouts/_header.html.slim
.navbar.navbar-expand-lg.navbar-light.bg-white
  = link_to  "InstaClone", root_path , class: 'navbar-brand'
  .collapse.navbar-collapse#navbarTogglerDemo02
    = render "posts/search", search_form: @search_form
    ul.navbar-nav.mt-2.mt-lg-0
      - if logged_in?
        li.nav-item
          = link_to new_post_path, class: 'nav-link' do
            i class = "far fa-image"
        li.nav-item
          = link_to '#', class: 'nav-link' do
            i class = "far fa-comments fa-lg"
        li.nav-item
          .dropdown
            a#dropdownMenuButton.nav-link.position-relative href="#" data-toggle="dropdown" aria-expanded="false" aria-haspopup="true"
              .far.fa-heart.fa-lg
              - if current_user.notifications.unread.present?
                .badge.badge-warning.navbar-badge.position-absolute
                  = current_user.notifications.unread.count
            #header-activities.dropdown-menu.dropdown-menu-right.m-0.p-0 aria-labelledby="dropdownMenuButton"
              =  render "shared/header_notifications"
        li.nav-item
          = link_to user_path(current_user), class: 'nav-link' do
            i class = "far fa-comments far fa-user fa-lg"
        li.nav-item
          = link_to "ログアウト", logout_path, method: :delete, class: 'nav-link'
      - else
        li.nav-item
          = link_to "ポスト一覧", root_path, class: 'nav-link'
        li.nav-item
          = link_to "ログイン", login_path, class: 'nav-link'

app/views/layouts/application.html.slim
doctype html
html
  head
    = display_meta_tags(default_meta_tags)
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all'
    = javascript_include_tag 'application'
  body
    = render "layouts/header"
    = render "shared/flash"
    main
      = yield
      = render "shared/swiper"
      = render "shared/modal"